framework:
    express:
        port: 8182
    database:
        type:     mysql
        host:     127.0.0.1
        name:     npm_lyrics_dev
        username: root
        password: frenchfrog
        # sqlite:
        #     path: path/to/database.sqlite

my_stuff:
    name: Romain
    age:  31

firebase:
    apiKey: "AIzaSyCA_esrGJt5XAFEwPqcZFSXHNN944NgShk"
    authDomain: "blank-159318.firebaseapp.com"
    databaseURL: "https://blank-159318.firebaseio.com"
    projectId: "blank-159318"
    storageBucket: "blank-159318.appspot.com"
    messagingSenderId: "914202577156"
