framework:
    express:
        port: 8182
    # database:
    #     type:     mysql
    #     host:     127.0.0.1
    #     name:     npm_lyrics_dev
    #     username: ben
    #     password: zepassword
    #     # sqlite:
    #     #     path: path/to/database.sqlite

my_stuff:
    name: Romain
    age:  31
